CREATE TABLE IF NOT EXISTS pemustakas (
  id VARCHAR(200) PRIMARY KEY,
  study_program_id VARCHAR(200) NOT NULL,
  departement_id VARCHAR(200) NOT NULL,
  role_id VARCHAR(200) NOT NULL,
  user_id VARCHAR(200) NOT NULL,
  member_code VARCHAR(20) NOT NULL,
  fullname VARCHAR(255) NOT NULL,
  identity_number VARCHAR(50) NOT NULL,
  year_gen CHAR(4),
  gender ENUM('Pria', 'Wanita', ''),
  telp CHAR(13),
  birth_date CHAR(10),
  address TEXT,
  is_active ENUM('1', '0')  DEFAULT '0',
  is_collected_final_project ENUM('1', '0') DEFAULT '0',
  is_collected_internship_report ENUM('1', '0') DEFAULT '0',
  avatar VARCHAR(255),
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  CONSTRAINT FOREIGN KEY (study_program_id) REFERENCES study_programs(id),
  CONSTRAINT FOREIGN KEY (departement_id) REFERENCES departements(id),
  CONSTRAINT FOREIGN KEY (role_id) REFERENCES roles(id),
  CONSTRAINT FOREIGN KEY (user_id) REFERENCES users(id)
)ENGINE=InnoDB;