CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(200) PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
)ENGINE=InnoDB;