// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	request "github.com/arvinpaundra/repository-api/models/web/mailing/request"
)

// MailingService is an autogenerated mock type for the MailingService type
type MailingService struct {
	mock.Mock
}

// SendForgotPasswordWithTokenExpiration provides a mock function with given fields: ctx, req
func (_m *MailingService) SendForgotPasswordWithTokenExpiration(ctx context.Context, req request.SendEmailForgotPasswordRequest) error {
	ret := _m.Called(ctx, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, request.SendEmailForgotPasswordRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendRepositoryAccepted provides a mock function with given fields: ctx, pemustakaId
func (_m *MailingService) SendRepositoryAccepted(ctx context.Context, pemustakaId string) error {
	ret := _m.Called(ctx, pemustakaId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, pemustakaId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendRequestAccessAccepted provides a mock function with given fields: ctx, pemustakaId
func (_m *MailingService) SendRequestAccessAccepted(ctx context.Context, pemustakaId string) error {
	ret := _m.Called(ctx, pemustakaId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, pemustakaId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMailingService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMailingService creates a new instance of MailingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMailingService(t mockConstructorTestingTNewMailingService) *MailingService {
	mock := &MailingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
