// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/arvinpaundra/repository-api/models/domain"
	mock "github.com/stretchr/testify/mock"
)

// CollectionRepository is an autogenerated mock type for the CollectionRepository type
type CollectionRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, collectionId
func (_m *CollectionRepository) Delete(ctx context.Context, collectionId string) error {
	ret := _m.Called(ctx, collectionId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, collectionId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, keyword, visibility, limit, offset
func (_m *CollectionRepository) FindAll(ctx context.Context, keyword string, visibility string, limit int, offset int) ([]domain.Collection, int, error) {
	ret := _m.Called(ctx, keyword, visibility, limit, offset)

	var r0 []domain.Collection
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) []domain.Collection); ok {
		r0 = rf(ctx, keyword, visibility, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Collection)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) int); ok {
		r1 = rf(ctx, keyword, visibility, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, string, int, int) error); ok {
		r2 = rf(ctx, keyword, visibility, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindById provides a mock function with given fields: ctx, collectionId
func (_m *CollectionRepository) FindById(ctx context.Context, collectionId string) (domain.Collection, error) {
	ret := _m.Called(ctx, collectionId)

	var r0 domain.Collection
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Collection); ok {
		r0 = rf(ctx, collectionId)
	} else {
		r0 = ret.Get(0).(domain.Collection)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, collectionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *CollectionRepository) Save(ctx context.Context, _a1 domain.Collection) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Collection) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, _a1, collectionId
func (_m *CollectionRepository) Update(ctx context.Context, _a1 domain.Collection, collectionId string) error {
	ret := _m.Called(ctx, _a1, collectionId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Collection, string) error); ok {
		r0 = rf(ctx, _a1, collectionId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCollectionRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewCollectionRepository creates a new instance of CollectionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCollectionRepository(t mockConstructorTestingTNewCollectionRepository) *CollectionRepository {
	mock := &CollectionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
